name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - pytorch==2.1.0
  - torchaudio==0.16.0
  - torchvision==2.1.0
  - pytorch-cuda=11.8
  - tqdm
  - pip:
      - wheel
      - gaussian-splatting-src/submodules/diff-gaussian-rasterization
      - gaussian-splatting-src/submodules/simple-knn
