name: gaussian_splatting
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch-cuda=11.8
  - plyfile=0.8.1
  - python=3.8
  - pip=22.3.1
  - pytorch=2.0.0
  - torchaudio=2.0.0
  - torchvision=0.15.0
  - tqdm
  - pip:
      - wheel
      - gaussian-splatting-src/submodules/diff-gaussian-rasterization
      - gaussian-splatting-src/submodules/simple-knn
